### ISSUE TITLE
DNS lookup fails for mxutils.com domain

### ISSUE THREAD

**Issue by mmccaff** [polera/rblwatch#10]
Hi James,

mxutils.com no longer resolves, so neither the API or http://www.mxutils.com/ web site can be used. Has this wonderful service gone away?

Matt

**Comment by polera** [comment]
Hi Matt,

Yikes!  I let the domain name lapse.  I just renewed it, so things should be back to normal momentarily.

Thanks for the heads up!
- James

**Comment by mmccaff** [comment]
Excellent, things are back to normal. Thank you!
